[package]
name = "pop-tiler-service"
description = "Simple drop-in microservice for integrating with pop-tiler"
version = "0.1.0"
license = "LGPL-3.0-only"
edition = "2018"

[dependencies]
async-channel = "1.6.1"
thiserror = "1.0.28"
ghost-cell = "0.2"
pop-tiler = { path = "../" }